name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Generate Snake for Light Mode
      - name: Generate Snake Animation (Light Mode)
        uses: Platane/snk@v3
        with:
          github_user_name: AKris15
          color_snake: "#000000" # Black Snake
          color_dots: "#800000,#B22222,#FF0000,#FF6347" # Dark to Light Red Commits
          color_background: "#FFFFFF" # White Background
          outputs: dist/github-contribution-grid-snake-light.svg

      # Generate Snake for Dark Mode
      - name: Generate Snake Animation (Dark Mode)
        uses: Platane/snk@v3
        with:
          github_user_name: AKris15
          color_snake: "#FFFFFF" # White Snake
          color_dots: "#800000,#B22222,#FF0000,#FF6347" # Dark to Light Red Commits
          color_background: "#000000" # Black Background
          outputs: dist/github-contribution-grid-snake-dark.svg
          

      # Generate GIFs separately
      - name: Generate Snake GIF (Light Mode)
        run: |
          docker run --rm ghcr.io/platane/snk generate --github-user AKris15 --output dist/github-contribution-grid-snake-light.gif --color-snake "#000000" --color-dots "#800000,#B22222,#FF0000,#FF6347" --color-background "#FFFFFF"
      
      - name: Generate Snake GIF (Dark Mode)
        run: |
          docker run --rm ghcr.io/platane/snk generate --github-user AKris15 --output dist/github-contribution-grid-snake-dark.gif --color-snake "#FFFFFF" --color-dots "#800000,#B22222,#FF0000,#FF6347" --color-background "#000000"

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add dist/
          git commit -m "Updated Snake Contribution Graph 🐍" || echo "No changes to commit"
          git push origin main

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
