# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Generate the Snake Contribution Graph with custom colors and dark background
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: AKris15
          outputs: dist/github-contribution-grid-snake.svg, dist/github-contribution-grid-snake.gif
          color_snake: "#FFFFFF" # White Snake
          color_dots: "#FF0000,#FF0000" # Red commits
          color_background: "#000000" # Dark background (Black)

      # Commit and push changes
      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add dist/
          git commit -m "Updated Snake Contribution Graph 🐍" || echo "No changes to commit"
          git push origin main

      # Deploy the Snake animation to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
